# Generated by Django 5.0.6 on 2024-05-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(max_length=10, unique=True)),
                ('resource_name', models.CharField(max_length=50, unique=True)),
                ('resource_description', models.CharField(max_length=300)),
                ('resource_content', models.CharField(max_length=1000)),
                ('resource_branch', models.CharField(choices=[('IGS', 'Imperial Guard Resource'), ('INS', 'Imperial Navy Resource'), ('IAS', 'Imperial Airforce Resource'), ('AAS', 'Adeptus Astartes Resource')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_DOID', models.CharField(max_length=50, unique=True)),
                ('member_discord_name', models.CharField(max_length=100, unique=True)),
                ('member_discord_id', models.CharField(max_length=100)),
                ('member_game_name', models.CharField(max_length=100)),
                ('member_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_date_joined', models.DateTimeField(auto_now_add=True)),
                ('member_date_of_birth', models.DateField()),
                ('member_rank', models.CharField(choices=[('Aly', 'Allied Member'), ('Whsd', 'Whiteshield'), ('ARct', 'Armsman Recruit'), ('VApr', 'Voidsman Apprentice'), ('Gd3', 'Guardsman 3rd Class'), ('Vdm', 'Voidsman'), ('Amn', 'Armsman'), ('Gd2', 'Guardsman 2rd Class'), ('Gd1', 'Guardsman 1st Class'), ('SVdm', 'Senior Voidsman'), ('SAmn', 'Senior Armsman'), ('GdSp', 'Specialist Guardsman'), ('GdV', 'Veteran Guardsman'), ('GdSn', 'Senior Guardsman'), ('MVdm', 'Master Voidsman'), ('MAmn', 'Master Armsman'), ('BAst', 'Brother Astartes'), ('LCpl', 'Lance Corporal'), ('LPO', 'Lance Petty Officer'), ('Cpl', 'Corporal'), ('PO', 'Petty Officer'), ('Sgt', 'Sergeant'), ('SPO', 'Senior Petty Officer'), ('SeSg', 'Senior Sergeant'), ('MPO', 'Master Petty Officer'), ('StSg', 'Staff Sergeant'), ('CPO', 'Chief Petty Officer'), ('CSgt', 'Color Sergeant'), ('MCPO', 'Master Chief Petty Officer'), ('SAst', 'Sergeant Astartes'), ('WOC', 'Warrant Officer Cadet'), ('NWOC', 'Naval Warrant Officer Cadet'), ('WO2', 'Warrant Officer Class 2'), ('NWO2', 'Naval Warrant Officer Class 2'), ('WO1', 'Warrant Officer Class 1'), ('NWO1', 'Naval Warrant Officer Class 1'), ('CWO', 'Chief Warrant Officer'), ('NCWO', 'Naval Chief Warrant Officer'), ('OCa', 'Officer Cadet'), ('3Lt', '3rd Lieutenant'), ('JEns', 'Junior Ensign'), ('2Lt', '2nd Lieutenant'), ('Ens', 'Ensign'), ('1Lt', '1st Lieutenant'), ('LtJG', 'Lieutenant Junior Grade'), ('Cpt', 'Captain'), ('Lt', 'Lieutenant'), ('LAst', 'Lieutenant Astartes'), ('Maj', 'Major'), ('LCdr', 'Lieutenant Commander'), ('LCo', 'Lieutenant Colonel'), ('Cdr', 'Commander'), ('Col', 'Colonel'), ('Capt', 'Captain'), ('LCpt', 'Lord Captain'), ('CAst', 'Captain Astartes'), ('Cdre', 'Commadore'), ('BGe', 'Brigadier General'), ('RAdm', 'Rear Admiral'), ('MGe', 'Major General'), ('LGe', 'Lieutenant General'), ('VAdm', 'Vice Admiral'), ('Gen', 'General'), ('Adm', 'Admiral'), ('HAdm', 'High Admiral'), ('LdGn', 'Lord General'), ('LAdm', 'Lord Admiral'), ('DAst', 'Captain-Commander Astartes')], max_length=4)),
                ('member_status', models.CharField(choices=[('NAM', 'Not A member'), ('AWO', 'Away with out leave'), ('DIS', 'Discharged'), ('FRE', 'Friendly Member'), ('ALY', 'Allied Member'), ('RCT', 'Recruit'), ('ELA', 'Extended Leave of Absence'), ('LOA', 'Leave of Absence'), ('RET', 'Retired'), ('ACT', 'Active')], max_length=3)),
                ('member_last_promotion_date', models.DateField(blank=True, null=True)),
                ('member_leave_date', models.DateField(blank=True, null=True)),
                ('member_officer_note', models.TextField(blank=True, max_length=800, null=True)),
                ('member_rejoin_date', models.DateField(blank=True, null=True)),
                ('member_retired_date', models.DateField(blank=True, null=True)),
                ('member_backend_admin', models.BooleanField(default=False)),
                ('member_public_admin', models.BooleanField(default=False)),
                ('member_private_admin', models.BooleanField(default=False)),
                ('member_public_gm', models.BooleanField(default=False)),
                ('member_profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('member_is_recruiter', models.BooleanField(default=False)),
                ('member_unit_position', models.CharField(blank=True, choices=[('MEMB', 'Member'), ('TELE', 'Team Leader'), ('VICC', 'Vehicle Commander'), ('SQLE', 'Squad Leader'), ('SELE', 'Section Leader'), ('PLSG', 'Platoon Sergeant'), ('PLCO', 'Platoon Commander'), ('CO1S', 'Company Senior NCO'), ('COXO', 'Company Executive Officer'), ('COCO', 'Company Commander'), ('BASM', 'Battalion Sergeant Major'), ('BAXO', 'Battalion Executive Officer'), ('BACO', 'Battalion Commander')], max_length=4, null=True)),
                ('member_desired_MOS_to_replace', models.CharField(blank=True, choices=[('PMO', 'Primary MOS'), ('SM1', 'Secondary MOS 1'), ('SM2', 'Secondary MOS 2')], max_length=10, null=True)),
                ('member_commission_type', models.CharField(choices=[('ENL', 'Enlisted'), ('NCO', 'Non-Commisioned Officer'), ('SNC', 'Senior Non-Commisioned Officer'), ('WOF', 'Warrant Officer'), ('COF', 'Commisioned Officer')], max_length=10)),
                ('member_astartes', models.CharField(choices=[('NAA', 'Not an Astartes'), ('FAA', 'Failed Astartes Training'), ('BAA', 'Banned from Astartes Training'), ('AAA', 'Active Adeptus Astartes')], max_length=20)),
                ('member_sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_sponsors', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='MOS',
            fields=[
                ('MOS_code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('MOS_name', models.CharField(max_length=50)),
                ('MOS_description', models.TextField()),
                ('MOS_default_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('MOS_commision_type', models.CharField(choices=[('ENL', 'Enlisted'), ('NCO', 'Non-Commisioned Officer'), ('SNC', 'Senior Non-Commisioned Officer'), ('WOF', 'Warrant Officer'), ('COF', 'Commisioned Officer')], max_length=4)),
                ('MOS_Creation_date', models.DateField(auto_now_add=True)),
                ('MOS_active', models.BooleanField(default=False)),
                ('MOS_recruiting', models.BooleanField(default=False)),
                ('MOS_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Branch_MOS', to='api.branch')),
                ('MOS_deputy_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MOS_deputy_in_charge', to='api.member')),
                ('MOS_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MOS_in_charge', to='api.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_desired_MOS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MOS_desired', to='api.mos'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_primary_MOS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_mos', to='api.mos'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_secondary_MOS_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_mos_1', to='api.mos'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_secondary_MOS_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_mos_2', to='api.mos'),
        ),
        migrations.CreateModel(
            name='OverrideCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=20, unique=True)),
                ('o_code', models.CharField(max_length=6, unique=True)),
                ('o_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_code', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=10, unique=True)),
                ('policy_name', models.CharField(max_length=20, unique=True)),
                ('policy_branch', models.CharField(choices=[('IGP', 'Imperial Guard Policy'), ('INP', 'Imperial Navy Policy'), ('IAP', 'Imperial Airforce Policy'), ('AAP', 'Adeptus Astartes Policy')], max_length=3)),
                ('policy_description', models.CharField(max_length=500)),
                ('policy_enforcement_level', models.CharField(choices=[('LAX', 'Lax'), ('GEN', 'Generaly'), ('STR', 'Strict'), ('VSTR', 'Very Strict'), ('ESTR', 'Extra Strict')], max_length=5)),
                ('policy_created_date', models.DateField(auto_now_add=True)),
                ('policy_active', models.BooleanField()),
                ('policy_creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_policy', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_code', models.CharField(max_length=10, unique=True)),
                ('pr_member_to_promote_current_rank', models.CharField(choices=[('Aly', 'Allied Member'), ('Whsd', 'Whiteshield'), ('ARct', 'Armsman Recruit'), ('VApr', 'Voidsman Apprentice'), ('Gd3', 'Guardsman 3rd Class'), ('Vdm', 'Voidsman'), ('Amn', 'Armsman'), ('Gd2', 'Guardsman 2rd Class'), ('Gd1', 'Guardsman 1st Class'), ('SVdm', 'Senior Voidsman'), ('SAmn', 'Senior Armsman'), ('GdSp', 'Specialist Guardsman'), ('GdV', 'Veteran Guardsman'), ('GdSn', 'Senior Guardsman'), ('MVdm', 'Master Voidsman'), ('MAmn', 'Master Armsman'), ('BAst', 'Brother Astartes'), ('LCpl', 'Lance Corporal'), ('LPO', 'Lance Petty Officer'), ('Cpl', 'Corporal'), ('PO', 'Petty Officer'), ('Sgt', 'Sergeant'), ('SPO', 'Senior Petty Officer'), ('SeSg', 'Senior Sergeant'), ('MPO', 'Master Petty Officer'), ('StSg', 'Staff Sergeant'), ('CPO', 'Chief Petty Officer'), ('CSgt', 'Color Sergeant'), ('MCPO', 'Master Chief Petty Officer'), ('SAst', 'Sergeant Astartes'), ('WOC', 'Warrant Officer Cadet'), ('NWOC', 'Naval Warrant Officer Cadet'), ('WO2', 'Warrant Officer Class 2'), ('NWO2', 'Naval Warrant Officer Class 2'), ('WO1', 'Warrant Officer Class 1'), ('NWO1', 'Naval Warrant Officer Class 1'), ('CWO', 'Chief Warrant Officer'), ('NCWO', 'Naval Chief Warrant Officer'), ('OCa', 'Officer Cadet'), ('3Lt', '3rd Lieutenant'), ('JEns', 'Junior Ensign'), ('2Lt', '2nd Lieutenant'), ('Ens', 'Ensign'), ('1Lt', '1st Lieutenant'), ('LtJG', 'Lieutenant Junior Grade'), ('Cpt', 'Captain'), ('Lt', 'Lieutenant'), ('LAst', 'Lieutenant Astartes'), ('Maj', 'Major'), ('LCdr', 'Lieutenant Commander'), ('LCo', 'Lieutenant Colonel'), ('Cdr', 'Commander'), ('Col', 'Colonel'), ('Capt', 'Captain'), ('LCpt', 'Lord Captain'), ('CAst', 'Captain Astartes'), ('Cdre', 'Commadore'), ('BGe', 'Brigadier General'), ('RAdm', 'Rear Admiral'), ('MGe', 'Major General'), ('LGe', 'Lieutenant General'), ('VAdm', 'Vice Admiral'), ('Gen', 'General'), ('Adm', 'Admiral'), ('HAdm', 'High Admiral'), ('LdGn', 'Lord General'), ('LAdm', 'Lord Admiral'), ('DAst', 'Captain-Commander Astartes')], max_length=4)),
                ('pr_member_to_promote_proposed_rank', models.CharField(choices=[('Aly', 'Allied Member'), ('Whsd', 'Whiteshield'), ('ARct', 'Armsman Recruit'), ('VApr', 'Voidsman Apprentice'), ('Gd3', 'Guardsman 3rd Class'), ('Vdm', 'Voidsman'), ('Amn', 'Armsman'), ('Gd2', 'Guardsman 2rd Class'), ('Gd1', 'Guardsman 1st Class'), ('SVdm', 'Senior Voidsman'), ('SAmn', 'Senior Armsman'), ('GdSp', 'Specialist Guardsman'), ('GdV', 'Veteran Guardsman'), ('GdSn', 'Senior Guardsman'), ('MVdm', 'Master Voidsman'), ('MAmn', 'Master Armsman'), ('BAst', 'Brother Astartes'), ('LCpl', 'Lance Corporal'), ('LPO', 'Lance Petty Officer'), ('Cpl', 'Corporal'), ('PO', 'Petty Officer'), ('Sgt', 'Sergeant'), ('SPO', 'Senior Petty Officer'), ('SeSg', 'Senior Sergeant'), ('MPO', 'Master Petty Officer'), ('StSg', 'Staff Sergeant'), ('CPO', 'Chief Petty Officer'), ('CSgt', 'Color Sergeant'), ('MCPO', 'Master Chief Petty Officer'), ('SAst', 'Sergeant Astartes'), ('WOC', 'Warrant Officer Cadet'), ('NWOC', 'Naval Warrant Officer Cadet'), ('WO2', 'Warrant Officer Class 2'), ('NWO2', 'Naval Warrant Officer Class 2'), ('WO1', 'Warrant Officer Class 1'), ('NWO1', 'Naval Warrant Officer Class 1'), ('CWO', 'Chief Warrant Officer'), ('NCWO', 'Naval Chief Warrant Officer'), ('OCa', 'Officer Cadet'), ('3Lt', '3rd Lieutenant'), ('JEns', 'Junior Ensign'), ('2Lt', '2nd Lieutenant'), ('Ens', 'Ensign'), ('1Lt', '1st Lieutenant'), ('LtJG', 'Lieutenant Junior Grade'), ('Cpt', 'Captain'), ('Lt', 'Lieutenant'), ('LAst', 'Lieutenant Astartes'), ('Maj', 'Major'), ('LCdr', 'Lieutenant Commander'), ('LCo', 'Lieutenant Colonel'), ('Cdr', 'Commander'), ('Col', 'Colonel'), ('Capt', 'Captain'), ('LCpt', 'Lord Captain'), ('CAst', 'Captain Astartes'), ('Cdre', 'Commadore'), ('BGe', 'Brigadier General'), ('RAdm', 'Rear Admiral'), ('MGe', 'Major General'), ('LGe', 'Lieutenant General'), ('VAdm', 'Vice Admiral'), ('Gen', 'General'), ('Adm', 'Admiral'), ('HAdm', 'High Admiral'), ('LdGn', 'Lord General'), ('LAdm', 'Lord Admiral'), ('DAst', 'Captain-Commander Astartes')], max_length=4)),
                ('pr_reason', models.CharField(max_length=500)),
                ('pr_status', models.CharField(choices=[('NA', 'No Action'), ('DE', 'Denied'), ('AP', 'Approved'), ('AR', 'Approved and Reviewed')], max_length=40)),
                ('pr_member_to_promote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_promotion_request', to='api.member')),
                ('pr_override_code_used', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prs_code_used_on', to='api.overridecode')),
                ('pr_requesting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_requested_promotions', to='api.member')),
                ('pr_reviewed_by_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_reviewed_prs', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_code', models.CharField(max_length=10, unique=True)),
                ('ap_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_approvals', to='api.member')),
                ('ap_linked_promotion_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_members', to='api.promotionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRLCode', models.CharField(max_length=10, unique=True)),
                ('PRL_Policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='linked_policy', to='api.policyinfo')),
                ('PRL_Resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='linked_resource', to='api.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
                ('role_absolute_minimum_rank', models.CharField(choices=[('Aly', 'Allied Member'), ('Whsd', 'Whiteshield'), ('ARct', 'Armsman Recruit'), ('VApr', 'Voidsman Apprentice'), ('Gd3', 'Guardsman 3rd Class'), ('Vdm', 'Voidsman'), ('Amn', 'Armsman'), ('Gd2', 'Guardsman 2rd Class'), ('Gd1', 'Guardsman 1st Class'), ('SVdm', 'Senior Voidsman'), ('SAmn', 'Senior Armsman'), ('GdSp', 'Specialist Guardsman'), ('GdV', 'Veteran Guardsman'), ('GdSn', 'Senior Guardsman'), ('MVdm', 'Master Voidsman'), ('MAmn', 'Master Armsman'), ('BAst', 'Brother Astartes'), ('LCpl', 'Lance Corporal'), ('LPO', 'Lance Petty Officer'), ('Cpl', 'Corporal'), ('PO', 'Petty Officer'), ('Sgt', 'Sergeant'), ('SPO', 'Senior Petty Officer'), ('SeSg', 'Senior Sergeant'), ('MPO', 'Master Petty Officer'), ('StSg', 'Staff Sergeant'), ('CPO', 'Chief Petty Officer'), ('CSgt', 'Color Sergeant'), ('MCPO', 'Master Chief Petty Officer'), ('SAst', 'Sergeant Astartes'), ('WOC', 'Warrant Officer Cadet'), ('NWOC', 'Naval Warrant Officer Cadet'), ('WO2', 'Warrant Officer Class 2'), ('NWO2', 'Naval Warrant Officer Class 2'), ('WO1', 'Warrant Officer Class 1'), ('NWO1', 'Naval Warrant Officer Class 1'), ('CWO', 'Chief Warrant Officer'), ('NCWO', 'Naval Chief Warrant Officer'), ('OCa', 'Officer Cadet'), ('3Lt', '3rd Lieutenant'), ('JEns', 'Junior Ensign'), ('2Lt', '2nd Lieutenant'), ('Ens', 'Ensign'), ('1Lt', '1st Lieutenant'), ('LtJG', 'Lieutenant Junior Grade'), ('Cpt', 'Captain'), ('Lt', 'Lieutenant'), ('LAst', 'Lieutenant Astartes'), ('Maj', 'Major'), ('LCdr', 'Lieutenant Commander'), ('LCo', 'Lieutenant Colonel'), ('Cdr', 'Commander'), ('Col', 'Colonel'), ('Capt', 'Captain'), ('LCpt', 'Lord Captain'), ('CAst', 'Captain Astartes'), ('Cdre', 'Commadore'), ('BGe', 'Brigadier General'), ('RAdm', 'Rear Admiral'), ('MGe', 'Major General'), ('LGe', 'Lieutenant General'), ('VAdm', 'Vice Admiral'), ('Gen', 'General'), ('Adm', 'Admiral'), ('HAdm', 'High Admiral'), ('LdGn', 'Lord General'), ('LAdm', 'Lord Admiral'), ('DAst', 'Captain-Commander Astartes')], max_length=50)),
                ('role_minimum_rank', models.CharField(choices=[('Aly', 'Allied Member'), ('Whsd', 'Whiteshield'), ('ARct', 'Armsman Recruit'), ('VApr', 'Voidsman Apprentice'), ('Gd3', 'Guardsman 3rd Class'), ('Vdm', 'Voidsman'), ('Amn', 'Armsman'), ('Gd2', 'Guardsman 2rd Class'), ('Gd1', 'Guardsman 1st Class'), ('SVdm', 'Senior Voidsman'), ('SAmn', 'Senior Armsman'), ('GdSp', 'Specialist Guardsman'), ('GdV', 'Veteran Guardsman'), ('GdSn', 'Senior Guardsman'), ('MVdm', 'Master Voidsman'), ('MAmn', 'Master Armsman'), ('BAst', 'Brother Astartes'), ('LCpl', 'Lance Corporal'), ('LPO', 'Lance Petty Officer'), ('Cpl', 'Corporal'), ('PO', 'Petty Officer'), ('Sgt', 'Sergeant'), ('SPO', 'Senior Petty Officer'), ('SeSg', 'Senior Sergeant'), ('MPO', 'Master Petty Officer'), ('StSg', 'Staff Sergeant'), ('CPO', 'Chief Petty Officer'), ('CSgt', 'Color Sergeant'), ('MCPO', 'Master Chief Petty Officer'), ('SAst', 'Sergeant Astartes'), ('WOC', 'Warrant Officer Cadet'), ('NWOC', 'Naval Warrant Officer Cadet'), ('WO2', 'Warrant Officer Class 2'), ('NWO2', 'Naval Warrant Officer Class 2'), ('WO1', 'Warrant Officer Class 1'), ('NWO1', 'Naval Warrant Officer Class 1'), ('CWO', 'Chief Warrant Officer'), ('NCWO', 'Naval Chief Warrant Officer'), ('OCa', 'Officer Cadet'), ('3Lt', '3rd Lieutenant'), ('JEns', 'Junior Ensign'), ('2Lt', '2nd Lieutenant'), ('Ens', 'Ensign'), ('1Lt', '1st Lieutenant'), ('LtJG', 'Lieutenant Junior Grade'), ('Cpt', 'Captain'), ('Lt', 'Lieutenant'), ('LAst', 'Lieutenant Astartes'), ('Maj', 'Major'), ('LCdr', 'Lieutenant Commander'), ('LCo', 'Lieutenant Colonel'), ('Cdr', 'Commander'), ('Col', 'Colonel'), ('Capt', 'Captain'), ('LCpt', 'Lord Captain'), ('CAst', 'Captain Astartes'), ('Cdre', 'Commadore'), ('BGe', 'Brigadier General'), ('RAdm', 'Rear Admiral'), ('MGe', 'Major General'), ('LGe', 'Lieutenant General'), ('VAdm', 'Vice Admiral'), ('Gen', 'General'), ('Adm', 'Admiral'), ('HAdm', 'High Admiral'), ('LdGn', 'Lord General'), ('LAdm', 'Lord Admiral'), ('DAst', 'Captain-Commander Astartes')], max_length=50)),
                ('role_is_command', models.BooleanField(default=False)),
                ('role_has_short_range_radio', models.BooleanField(default=False)),
                ('role_has_long_range_radio', models.BooleanField(default=False)),
                ('role_can_be_in_charge', models.BooleanField(default=False)),
                ('role_primary_MOS', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_primary_MOS', to='api.mos')),
                ('role_secondary_MOS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_secondary_MOS', to='api.mos')),
                ('role_tertiary_MOS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_tertiary_MOS', to='api.mos')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=5)),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_description', models.TextField()),
                ('unit_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('unit_status', models.CharField(max_length=50)),
                ('unit_co', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_CO', to='api.member')),
                ('unit_xo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_XO', to='api.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_members', to='api.unit'),
        ),
    ]
